language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

script:
  - phpunit tests
  - ./tests/lint.sh

git:
  depth: 5
